// WeightHelpers.cpp
// Self-contained ROOT macro for deriving and applying data/MC weights from histograms
// Author: GitHub Copilot, 2025-07-31
// Usage (ROOT): .x WeightHelpers.cpp+("data.root","mc.root","histname","weights.txt",normalizeMode,underflowMode)
// normalizeMode: 0=raw, 1=normalize to integral, 2=normalize to density (integral/bin width)
// underflowMode: 0=weight 0 for under/overflow, 1=weight 1

#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <cmath>
#include <algorithm>
#include <stdexcept>
#include <iomanip>
#include "TFile.h"
#include "TH1.h"
#include "TTree.h"

struct WeightBin {
    double low, high, weight;
};

// Helper: Read TH1 from file
TH1* getHistFromFile(const std::string& fname, const std::string& hname) {
    TFile* f = TFile::Open(fname.c_str());
    if (!f || f->IsZombie()) throw std::runtime_error("Cannot open file: " + fname);
    TH1* h = dynamic_cast<TH1*>(f->Get(hname.c_str()));
    if (!h) throw std::runtime_error("Histogram not found: " + hname + " in " + fname);
    h->SetDirectory(0); // Detach from file
    f->Close();
    delete f;
    return h;
}

// Helper: Stub for TTree support (future)
void getHistFromTree(const std::string&, const std::string&, int, double, double) {
    std::cerr << "TTree support not implemented yet.\n";
}

// Normalize histogram: 0=raw, 1=integral, 2=density
void normalizeHist(TH1* h, int mode) {
    if (!h) return;
    if (mode == 1) {
        double integral = h->Integral();
        if (integral > 0) h->Scale(1.0/integral);
    } else if (mode == 2) {
        double integral = h->Integral();
        if (integral > 0) h->Scale(1.0/integral,"width");
    }
    // mode==0: do nothing
}

// Compare histograms: check binning
bool compareHistBinning(const TH1* h1, const TH1* h2) {
    if (!h1 || !h2) return false;
    if (h1->GetNbinsX() != h2->GetNbinsX()) return false;
    for (int i=1; i<=h1->GetNbinsX()+1; ++i) {
        if (std::abs(h1->GetBinLowEdge(i) - h2->GetBinLowEdge(i)) > 1e-6) return false;
    }
    return true;
}

// Derive weights and write to file
void deriveWeights(const std::string& dataFile, const std::string& mcFile, const std::string& histName, const std::string& outTxt,
                   int normalizeMode=0, int underflowMode=0) {
    TH1* hData = getHistFromFile(dataFile, histName);
    TH1* hMC   = getHistFromFile(mcFile, histName);
    normalizeHist(hData, normalizeMode);
    normalizeHist(hMC, normalizeMode);
    if (!compareHistBinning(hData, hMC)) {
        std::cerr << "Histogram binning mismatch!" << std::endl;
        return;
    }
    std::ofstream fout(outTxt);
    // Write provenance header
    fout << "# Weight file generated by WeightHelpers.cpp\n";
    fout << "# Date: " << __DATE__ << " " << __TIME__ << "\n";
    fout << "# Data file: " << dataFile << "\n";
    fout << "# MC file:   " << mcFile << "\n";
    fout << "# Histogram: " << histName << "\n";
    fout << "# Normalization mode: 0=raw, 1=integral, 2=density: " << normalizeMode << "\n";
    fout << "# Underflow/overflow mode: 0=weight 0, 1=weight 1: " << underflowMode << "\n";
    fout << "# bin_low bin_high weight\n";
    int nbins = hData->GetNbinsX();
    for (int i=1; i<=nbins; ++i) {
        double low = hData->GetBinLowEdge(i);
        double high = hData->GetBinLowEdge(i+1);
        double d = hData->GetBinContent(i);
        double m = hMC->GetBinContent(i);
        double w = (m > 0) ? (d/m) : 0.0;
        fout << std::setprecision(8) << low << " " << high << " " << w << "\n";
    }
    // Underflow/overflow
    if (underflowMode==0) {
        fout << "# Underflow/overflow bins assigned weight 0\n";
    } else {
        fout << "# Underflow/overflow bins assigned weight 1\n";
    }
    fout.close();
    std::cout << "Wrote weights to " << outTxt << std::endl;
    delete hData;
    delete hMC;
}

// Weight lookup class
class WeightHelper {
public:
    WeightHelper(const std::string& fname, int underflowMode=0) : underflowWeight_(underflowMode==0?0.0:1.0) {
        std::ifstream fin(fname);
        if (!fin) throw std::runtime_error("Cannot open weight file: " + fname);
        std::string line;
        while (std::getline(fin, line)) {
            if (line.empty() || line[0]=='#') continue;
            std::istringstream iss(line);
            double l, h, w;
            if (!(iss >> l >> h >> w)) continue;
            bins_.push_back({l, h, w});
        }
        fin.close();
    }
    double getWeight(double x) const {
        for (const auto& b : bins_) {
            if (x >= b.low && x < b.high) return b.weight;
        }
        // Underflow/overflow
        return underflowWeight_;
    }
private:
    std::vector<WeightBin> bins_;
    double underflowWeight_;
};

// Example usage as a macro
void WeightHelperExample() {
    WeightHelper w("weights.txt");
    std::cout << "Weight for x=50: " << w.getWeight(50) << std::endl;
}

// ROOT macro entry point
void WeightHelpers(const char* dataFile, const char* mcFile, const char* histName, const char* outTxt,
                  int normalizeMode=0, int underflowMode=0) {
    deriveWeights(dataFile, mcFile, histName, outTxt, normalizeMode, underflowMode);
}
